sentry:
  dsn: ${SENTRY_DSN}
  environment: dev
  release: "moring-dev@1.0.0"

file:
  upload-path: uploaded
  base-url: https://file.moring.one

decorator:
  datasource:
    p6spy:
      enable-logging: false