springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

sentry:
  dsn: ${SENTRY_DSN}
  environment: prod
  release: "moring-prod@1.0.0"

decorator:
  datasource:
    p6spy:
      enable-logging: false

file:
  upload-path: uploaded
  base-url: https://file.moring.one
